// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc3588.RobotMain;

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import edu.wpi.first.wpilibj.CANTalon;
import edu.wpi.first.wpilibj.RobotDrive;
import edu.wpi.first.wpilibj.Servo;
import edu.wpi.first.wpilibj.SpeedController;
import edu.wpi.first.wpilibj.Talon;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import edu.wpi.first.wpilibj.livewindow.LiveWindow;

/**
 * The RobotMap is a mapping from the ports sensors and actuators are wired into
 * to a variable name. This provides flexibility changing wiring, makes checking
 * the wiring easier and significantly reduces the number of magic numbers
 * floating around.
 */
public class RobotMap {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public static CANTalon acqConveyorArm;
    public static CANTalon acqArmRotate;
    public static CANTalon acqConveyorRobot;
    public static SpeedController driveSystemLeftMotor;
    public static SpeedController driveSystemRightMotor;
    public static RobotDrive driveSystemRobotDrive;
    public static CANTalon shootingLauncher;
    public static CANTalon climbingMotor;
    public static CANTalon defenseArm;
    public static Servo cameraXServo;
    public static Servo cameraYServo;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    public static void init() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        acqConveyorArm = new CANTalon(1);
        LiveWindow.addActuator("Acq", "ConveyorArm", acqConveyorArm);
        
        acqArmRotate = new CANTalon(0);
        LiveWindow.addActuator("Acq", "ArmRotate", acqArmRotate);
        
        acqConveyorRobot = new CANTalon(2);
        LiveWindow.addActuator("Acq", "ConveyorRobot", acqConveyorRobot);
        
        driveSystemLeftMotor = new Talon(1);
        LiveWindow.addActuator("DriveSystem", "LeftMotor", (Talon) driveSystemLeftMotor);
        
        driveSystemRightMotor = new Talon(0);
        LiveWindow.addActuator("DriveSystem", "RightMotor", (Talon) driveSystemRightMotor);
        
        driveSystemRobotDrive = new RobotDrive(driveSystemLeftMotor, driveSystemRightMotor);
        
        driveSystemRobotDrive.setSafetyEnabled(true);
        driveSystemRobotDrive.setExpiration(0.1);
        driveSystemRobotDrive.setSensitivity(0.5);
        driveSystemRobotDrive.setMaxOutput(1.0);
        driveSystemRobotDrive.setInvertedMotor(RobotDrive.MotorType.kRearLeft, true);
        shootingLauncher = new CANTalon(7);
        LiveWindow.addActuator("Shooting", "Launcher", shootingLauncher);
        
        climbingMotor = new CANTalon(5);
        LiveWindow.addActuator("Climbing", "Motor", climbingMotor);
        
        defenseArm = new CANTalon(6);
        LiveWindow.addActuator("Defense", "Arm", defenseArm);
        
        cameraXServo = new Servo(3);
        LiveWindow.addActuator("Camera", "XServo", cameraXServo);
        
        cameraYServo = new Servo(4);
        LiveWindow.addActuator("Camera", "YServo", cameraYServo);
        

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    }
}
